name: Deploy ASP.NET to Azure

on:
  push:
    branches:
      - main  # or master, depending on your repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./backend/backend.csproj

    - name: Build
      run: dotnet build --configuration Release ./backend/backend.csproj

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish ./backend/backend.csproj

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: tema-ai-app  # your Azure App Service name
        slot-name: production
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ./publish
